### ISSUE TITLE
Power

### ISSUE THREAD

**Issue by svnpenn** [sietseringers/MACAddressTool#1]
Do I need to power off, power on my modem after using this tool?

I cant seem to get a connection after changing the MAC

**Comment by sietseringers** [comment]
It should take effect immediately, but the last time I've touched or run this tool myself is more than two years ago. Your modem might have a whitelist of accepted MAC addresses, blocking any new one.

**Comment by svnpenn** [comment]
I have this one

http://netgear.com/home/products/networking/cable-modems-routers/CM400.aspx

**Comment by PhilipMur** [comment]
Is your computer getting it's I.P address DHCP or is it a static I.P address .
The problem with assigning a static I.P address is that the router maps the I.P to the mac address as the mac address is all the router cares about so either change your static I.P or set it to DHCP .

**Comment by sietseringers** [comment]
@svnpenn That doesn't help. It might or it might not be configured to use a whitelist of MAC-addresses.

**Comment by svnpenn** [comment]
@PhilipMur I have it set to "Obtain an IP address automatically". As soon as I
run this tool, it kicks off my connection until I restore the default MAC

@sietseringers you keep mentioning a MAC address whitelist, but you have yet to
say how I would check if my modem is enforcing one, or how to see what the
allowed MAC addresses are for my modem, or even if it is possible to me to check
such things. So you comments so far arent really helpful

**Comment by PhilipMur** [comment]
Are you changing wifi mac or ethernet mac addresses?
Is it a desktop or laptop?
Also if it is wifi you may need type in the wifi password again.
I have tried this code on my pc and laptops win 7 and win 10 it tested ok.

**Comment by svnpenn** [comment]
1. ethernet
2. desktop

**Comment by PhilipMur** [comment]
How long do you wait could take up to a minute to reconnect.

This is a tricky one but interesting none the less .

Are you testing via a virtual machine ,either vmbox or vmware etc..
As i know the mac has to be changed in the vm settings menu otherwise it will be rejected.

More and as much information as you could give would be great in finding a possible solution to this problem.

1) windows OS and version

2)make of ethernet card/motherboard etc

3)does the router have mac filtering enabled?

4)how long did you wait for the new mac to be accepted?

5)can you change the very last number or letter on your mac address(must equal a valid hexadecimal number when done) manually via device manager to test will it allow access as mac is broke into first 4 = vender id and last 4= unique id address .

**Comment by svnpenn** [comment]
@PhilipMur I dont think I want to continue troubleshooting with you, because you have left out a glaring question, which is my ISP could be causing the problem, so it appears you do not know what you are talking about. If you did, that would have been one of your first questions.

http://wikipedia.org/wiki/MAC_spoofing#New_hardware_for_existing_Internet_Service_Providers_.28ISP.29

**Comment by PhilipMur** [comment]
I am glad to hear that someone who takes the time to help you in fixing your issue is being unhelpful and is regarded as not knowing what they are talking about.

I would suggest talking to an IT engineer who would gladly help you to change your mac address and charge you well for it too in the proccess.

Explain in all your greatness how your isp could possibly know all your mac addresses on your local network.

If admin could close this issue as human issues cannot be solved here and not enough information was given on the issue observed.

 I have used this code to change the mac addresses on many devices and works perfectly a credit to the develper.

**Comment by sietseringers** [comment]
@PhilipMur I quite agree. Thanks for your helpfulness and kind words!

**Comment by svnpenn** [comment]
I fixed the issue myself:

> For the ISP to discover the new device or MAC address and assign a new IP
> address, The old MAC address must be cleared from the Cable Modem. **To do
> this, a cold boot of the Cable Modem is required.** That means the Modem MUST
> be powered off.

http://shnerdlys.com/index.php/change-your-external-ip
