### ISSUE TITLE
Any licensing for the code and application?

### ISSUE THREAD

**Issue by zbalkan** [sietseringers/MACAddressTool#6]
Hi,

Since there is no license provided with the code it is currently a [No License](https://choosealicense.com/no-permission/). 

> If you find software that doesn’t have a license, that generally means you have no permission from the creators of the software to use, modify, or share the software. Although a code host such as GitHub may allow you to view and fork the code, this does not imply that you are permitted to use, modify, or share the software for any purpose.

Is it possible to add a license for the repository?

**Comment by sietseringers** [comment]
Hi!

I have added the MIT license. However, I am also going to archive this repository. This is because I have not maintained this repository for years and I don't plan to; I don't have Windows anymore and I don't expect that to change.

As the license itself states, anyone that wishes to should feel free to use or fork this repository for whatever purpose.
